### Data Cleaning

In [ ]:
# import necessary libraries
import pandas as pd

In [ ]:
# load the dataset
df = pd.read_excel('../dataset/Dataset.xlsx')
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [ ]:
# Physical check of last rows
df.tail()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [16]:
# Check for duplicate rows
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [ ]:
# Check for missing values
print("\nMissing values:")
print(df.isna().sum())

Missing values:
OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [ ]:
# Handle missing values in the 'CouponCode' column by filling them with 'No Coupon'
df['CouponCode'] = df['CouponCode'].fillna('No Coupon')

In [ ]:
# Check the value counts of the 'CouponCode' column after handling missing values
df['CouponCode'].value_counts()

CouponCode
FREESHIP     313
No Coupon    309
WINTER15     292
SAVE10       286
Name: count, dtype: int64

In [ ]:
# Check for missing values again after handling them(Validating the changes)
print(df.isna().sum())

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [ ]:
# Check for duplicate Order IDs and Tracking Numbers
print("Duplicate Order IDs:", df['OrderID'].duplicated().sum())
print("Duplicate Tracking Numbers:", df['TrackingNumber'].duplicated().sum())

Duplicate Order IDs: 0
Duplicate Tracking Numbers: 0

In [ ]:
# Check the data types of each column
df.dtypes

OrderID                       str
Date               datetime64[us]
CustomerID                    str
Product                       str
Quantity                    int64
UnitPrice                 float64
ShippingAddress               str
PaymentMethod                 str
OrderStatus                   str
TrackingNumber                str
ItemsInCart                 int64
CouponCode                    str
ReferralSource                str
TotalPrice                float64
dtype: object

In [ ]:
# Check for negative or zero values in Quantity, UnitPrice, TotalPrice, and ItemsInCart columns
print("Quantity <= 0:", (df['Quantity'] <= 0).sum())
print("UnitPrice <= 0:", (df['UnitPrice'] <= 0).sum())
print("TotalPrice <= 0:", (df['TotalPrice'] <= 0).sum())
print("ItemsInCart <= 0:", (df['ItemsInCart'] <= 0).sum())

Quantity <= 0: 0
UnitPrice <= 0: 0
TotalPrice <= 0: 0
ItemsInCart <= 0: 0

In [ ]:
# Check for incorrect TotalPrice values by comparing it with the calculated total (Quantity * UnitPrice)
calculated_total = df['Quantity'] * df['UnitPrice']

print(
    "Incorrect TotalPrice:",
    (abs(df['TotalPrice'] - calculated_total) > 0.01).sum()
)

Incorrect TotalPrice: 0

In [ ]:
# Check for ItemsInCart values that are less than Quantity values
print(
    "ItemsInCart < Quantity:",
    (df['ItemsInCart'] < df['Quantity']).sum()
)

ItemsInCart < Quantity: 0

In [ ]:
# Check for unique values in categorical columns
print(df['PaymentMethod'].unique())
print(df['OrderStatus'].unique())
print(df['Product'].unique())
print(df['ReferralSource'].unique())
print(df['CouponCode'].unique())

<StringArray>
['Debit Card', 'Online', 'Credit Card', 'Gift Card', 'Cash']
Length: 5, dtype: str
<StringArray>
['Shipped', 'Cancelled', 'Returned', 'Delivered', 'Pending']
Length: 5, dtype: str
<StringArray>
['Monitor', 'Phone', 'Tablet', 'Chair', 'Printer', 'Laptop', 'Desk']
Length: 7, dtype: str
<StringArray>
['Instagram', 'Referral', 'Email', 'Facebook', 'Google']
Length: 5, dtype: str
<StringArray>
['SAVE10', 'FREESHIP', 'No Coupon', 'WINTER15']
Length: 4, dtype: str

In [ ]:
# Check the earliest and latest dates in the 'Date' column
print("Earliest date:", df['Date'].min())
print("Latest date:", df['Date'].max())

Earliest date: 2023-01-01 00:00:00
Latest date: 2025-06-30 00:00:00